### PR TITLE
Implement crop area padding and radius

### PR DESCRIPTION
**Pull request by Frezyx**
### Hello @xclud 👋
I implement padding and radius for crop area. 
I want this functionality in case to implement bank cards preview image selector.

Functionality that i made not broke currently package logic and can be very useful.
I hope you can watch and make review of this pull request in near future ❤️ 
#### Preview:
telegram-cloud-photo-size-2-5472092668352905056-y

### CODE REVIEW

**Comment by xclud** [comment]
Hi @Frezyx,
Thank you for the contribution.

I wrote some comments. We need to address them before merging :)

**Comment by Frezyx** [comment]
Hello @exclude !
I am currently fixed merge conflicts and test my changes. Everything works!
Are we ready to merge it ?

**Comment by xclud** [comment]
Hi @Frezyx,

There are still lots of unneeded changes. Please only commit the changes related to the feature you are adding. Do not change the formatting. Do not modify the example files (only modify the lines which show your feature; e.g. do not modify macOS related files).

**Comment by xclud** [comment]
If you wish to format the code and/or add the trailing commas, Please submit another PR.

**Comment by Frezyx** [comment]
Hi @xclud !
Unneeded changes was removed👌

**Comment by xclud** [comment]
@Frezyx Thank you. I did merge :)

**Pull request merged**
