### PR TITLE
Support setting the width or height of the output image

### PR DESCRIPTION
**Pull request by ipcjs**
#29

### CODE REVIEW

**Comment by xclud** [comment]
I am trying to guess what you indent to do. Just to clarify, `pixelRatio` is not a sort of aspect-ratio. It is the ratio of physical pixels to logical pixels. For example. on my phone, every 4 physical pixel is considered 1 logical pixel.

Can you please shed some light on this?

**Comment by ipcjs** [comment]
The actual effect of the pixelRatio parameter is similar to scaling([source code](https://github.com/flutter/flutter/blob/beta/packages/flutter/lib/src/rendering/layer.dart/#L1199)). So we can control the size of the output image by modifying this parameter.

If the widget size is 100x100 and we want to get a 200x200 image, pixelRatio should be set to 200/100=2, calling crop({pixelRatio: 2}). Or just call crop{targetWidth: 200}, the method internally will calculate the appropriate pixelRatio for us.

**Comment by xclud** [comment]
Thank you @ipcjs. I will review this PR with more details.

**Comment by nwparker** [comment]
This is a nice addition. I was going to test this code out, but sadly it's a bit of a pain to merge with the latest master. I'll wait on one of you 2 to merge.

But if that's the only thing stalling this from getting merged, I'm happy to help perform the rebase. Just didn't want to do "wasted" work

**Comment by nwparker** [comment]
Not sure what was the best way to go about this, but I created a new rebased PR:
https://github.com/xclud/flutter_crop/pull/44

PTAL both of you 👍

**Comment by ipcjs** [comment]
If flutter_crop does not consider adding this feature. 
Can you consider adding a method to expose the size of the renderObject so that I can implement this method externally.

**Comment by xclud** [comment]
You can initialize the Crop widget with aspect ratio you want (imagewidth/imageheight) and then after cropping resize the output image to the desired image size (imagewidth x imageheight). you can use this package https://pub.dev/packages/image for resizing.

**Pull request closed without merging**
